version: "3.9"

services:
  pgdb:
    image: postgres
    container_name: pgdb
    restart: on-failure
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - env/db.env
  django:
    build: .
    container_name: django
    restart: always
    volumes:
      - .:/usr/src/innotter
    ports:
      - "8000:8000"
    env_file:
      - env/.env
      - env/db.env
    depends_on:
      - pgdb
  localstack:
    image: localstack/localstack
    container_name: localstack
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "4566:4566"
    env_file:
      - env/.env
      - env/localstack.env
volumes:
  pgdata:
